### ISSUE TITLE
Error in New Order Request - Check Yields Infinite Value

### ISSUE THREAD

**Issue by ledaks** [daroczig/binancer#16] opened 2021-01-03 17:57 UTC
I found an issue with placing orders using the "new order" function.

Line 723 of "binancer/R/binance.R" reads the following:

# work around the limitation of %% (e.g. 200.1 %% 0.1 = 0.1 !!)
    quot <- (quantity - filters[filterType == 'LOT_SIZE', minQty]) / filters[filterType == 'LOT_SIZE', stepSize]
    stopifnot(abs(quot - round(quot)) < 1e-10)

Filters, is a data table specifying some of the order limits (ie max price, max quantity, etc). Filters are specific to each coin. Using the example of "BTCUSDT", the filters value for 

 filters[filterType == 'LOT_SIZE', stepSize] is 0. When you evaluate quot, it yields quot = x / 0, which is an infinite number.

With that, it is not possible to successfully evaluate 'abs(quot - round(quot)) < 1e-10'.

Is there any workaround to this issue?

Much appreciated!

**Comment by PatronMaster** [comment] 2021-02-13 11:55
Hi Jgroves10,

I am using a very old version of this package and still work. 
![image](https://user-images.githubusercontent.com/7825849/107849249-e87d3e00-6df1-11eb-9de6-d093150088b4.png)

A soon I have time I will make a fork with my current version. I think this team is not working on this project.

**Comment by jgroves10** [comment] 2021-02-13 15:16
Hi PatronMaster,

Thank you for the reply! I've realised the issue was being caused by me using the testnet API, which has different step sizes than that of the real mode for some pairs. 

The old package is really good too! I look forward to using your current version when released.

Thanks

**Comment by timothyjgraham** [comment] 2021-03-04 06:06
> Hi Jgroves10,
> 
> I am using a very old version of this package and still work.
> ![image](https://user-images.githubusercontent.com/7825849/107849249-e87d3e00-6df1-11eb-9de6-d093150088b4.png)
> 
> A soon I have time I will make a fork with my current version. I think this team is not working on this project.

Hi @PatronMaster , I am wondering if you might be able to share your updated repository to fix this issue? Thank you!

**Comment by daroczig** [comment] 2021-11-26 00:28
Closing as seems to be a duplicate of #14

**Closed by daroczig** 2021-11-26 00:28 UTC
